### ISSUE TITLE
Source directory does not exist on Cmake

### ISSUE THREAD

**Issue by alignwaivers** [tobanteAudio/modEQ#1]
Hey this seems like an awesome project, trying to get it running on on Ubuntu Bionic (KDE Neon)

I'm running from the root directory of the project after cloning recursively

Getting this error:
> CMake Error: The source directory "" does not exist.

**Comment by tobiashienzsch** [comment]
What command are you trying to run? Maybe you have an older CMake version. Try replacing the `-S.` with `-H.`

So the commands would be:

```
cd modEQ
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release
```

I'm running on PopOS 20.04.
